# SPDX-FileCopyrightText: 2020 Dimitris Lampridis <dlampridis@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Lint and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,gui]"
    - name: Test with pytest
      run: pytest
    - name: Analysing the code with pylint
      run: pylint src/pydevialet_expert_nonpro tests gui
