# SPDX-FileCopyrightText: 2020 Dimitris Lampridis <dlampridis@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Pylint

on: [push, workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install uv
        uv sync --group dev --group gui
    - name: Analysing the code with pylint
      run: |
        uv run pylint $(git ls-files '*.py' | grep -v 'src/backend\.py')
