# SPDX-FileCopyrightText: 2020 Dimitris Lampridis <dlampridis@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Install uv
      run: pip install uv
    - name: Analysing the repository with REUSE
      run: uvx reuse lint
